name: tools_tests
on:  
  pull_request_target:  
    types: [opened, synchronize, reopened]  
    branches:   
      - main  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v2  
    - name: Run a one-line script  
      run: echo Hello, world! 
